export const allSkills = [
  {
    title: "Core Languages",
    description: ["HTML5", "CSS3", "JavaScript (ES6+)", "TypeScript"],
  },
  {
    title: "Frontend Libraries & Frameworks",
    description: [
      "React.js",
      "Next.js",
      "Tailwind CSS",
      "i18n (Internationalization)",
      "React Hook Form",
      "Zod",
      "Yup",
      "Material UI",
      "Chakra UI",
      "Bootstrap",
      "Styled Components",
      "Framer Motion",
      "SASS",
      "PugJS",
    ],
  },
  {
    title: "State Management & Data Fetching",
    description: [
      "TanStack React Query",
      "Redux",
      "Redux Toolkit",
      "Redux Toolkit Query",
      "Zustand",
      "Context API",
      "Axios",
      "REST APIs",
    ],
  },
  {
    title: "Optimization & Debugging",
    description: [
      "Performance Optimization",
      "Problem Solving",
      "SEO (Search Engine Optimization)",
      "Debugging (Chrome DevTools, React DevTools)",
    ],
  },
  {
    title: "Backend & Database",
    description: ["Firebase", "Supabase"],
  },
  {
    title: "Design & Responsive Development",
    description: [
      "Responsive Design",
      "Cross-Browser Compatibility",
      "UI/UX Principles",
      "Understanding of layout aesthetics",
    ],
  },
  {
    title: "Version Control & Collaboration",
    description: ["Git", "GitHub", "Gitlab", "Code Review", "Postman", "NPM"],
  },
  {
    title: "Soft Skills",
    description: [
      "Teamwork",
      "Communication",
      "Time Management",
      "Presentation Skills",
      "Willingness to Learn",
      "Effective collaboration",
      "Proficient in English",
      "Negotiation",
      "Active Listening",
      "Attention to Detail",
      "Accountability",
      "Emotional Intelligence",
      "Excellent Analytical Skills",
      "Multitasking Skills",
    ],
  },
];
